### ISSUE TITLE
Executable not found during launch

### ISSUE THREAD

**Issue by FrederickDeny** [E4S-Project/e4s-cl#30]
When launching a container using e4s-cl to run an executable, command not found error is thrown:

```
$ e4s-cl launch --profile init_runsi  mpirun -np 4 a.out
38860 on cyclops: /.e4s-cl/script: line 18: a.out: command not found
```

But giving the absolute path for the executable makes it run without issues:
```
$ e4s-cl launch --profile init_runsi  mpirun -np 4 $PWD/a.out
We have 4 processes.
Process 1 reporting for duty.
Process 2 reporting for duty.
Process 3 reporting for duty.
```

It looks like singularity (the container technology used with this profile) doesn't always keep the user's working directory within the launched container.

**Comment by spoutn1k** [comment]
After experimentation, this is normal behaviour, `mpirun` has to be given a relative path to execute a binary.

**Comment by FrederickDeny** [comment]
My bad, the initial launch command was indeed using a relative path, ie, the following:

```
$ e4s-cl launch --profile init_runsi  mpirun -np 4 ./a.out
35665 on cyclops.stor: /.e4s-cl/script: line 18: ./a.out: No such file or directory
```

Otherwise, it seems like my pwd changes when launching with e4s-cl:
```
$ pwd
/home/users/fdeny/ContainerLauncher/helloworldprogram
$ e4s-cl launch --profile OpenMPI_4.0.2 mpirun -np 4 pwd
/home/users/fdeny
/home/users/fdeny
/home/users/fdeny
/home/users/fdeny
```
