### ISSUE TITLE
Errors parsing launcher CLI

### ISSUE THREAD

**Issue by spoutn1k** [E4S-Project/e4s-cl#31]
WI4MPI's launcher expects underlying launcher arguments to be passed to the `-E` option in a string. To use OpenMPI's `--oversubscribe`, one should use:

```
mpirun -E '--oversubscribe' -np 8 -from mpich -to openmpi ./bin/lu.A.8.mvapich2
```

This string can contain spaces, which may confuse the current parsing system. Using `shlex` or a similar dedicated parser might resolve this issue.

**Comment by FrederickDeny** [comment]
This was indeed resolved through using shlex
